@Entity @Table(name="EMP")
public class Employee {
	public enum Type {FULL, PART_TIME};
	protected Employee(){}
	public Employee(String name, Type type){
		this.name = name; this.type = type;
	}
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	long id;
	@Enumerated(EnumType.STRING)
	@Column(name="EMP_TYPE", nullable=false)
	Type type;
	@Lob byte[] picture;
	String name;
}

create table EMP (
	id bigint generated by default as identity (start with 1),
	picture longvarbinary,
	EMP_TYPE varchar(255) not null,
	primary key (id)
)